server.port: 8191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwtdemo?createDatabaseIfNotExist=true
    username: root
    password: example
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
    show-sql: true


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days